server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # set false for production
  datasource:
    url: 'jdbc:postgresql://ec2-54-170-109-0.eu-west-1.compute.amazonaws.com:5432/dd0euod6do05sh'
    username: ${jdbc.user}
    password: ${jdbc.pass}
    hikari:
      minimumIdle: 5
      maximumPoolSize: 40
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: Telegram

management:
  endpoints:
    web:
      exposure:
        include: '*'

telegrambot:
  botUsername: '@Botting_bot_bot'
  botToken: 1196132719:AAFavCJ8hdXjLOarub2MsQANwDqP6urzfpQ
  webHookPath: 'https://7903f7b968ca.ngrok.io'
